### PR TITLE
Easy way to add custom extension on Android

### PR DESCRIPTION
**Pull request by andysdds**

### CODE REVIEW

**Comment by yasirkula** [comment]
Won't this `intent-filter` cause the Unity app to be included in the list of apps presented to the user when another application calls startActivityForResult for ACTION_VIEW? This would be very bad for UX. I think it would be enough fileTypes to `new string[] { "*/*" };`?

**Comment by andysdds** [comment]
Thank you for your reply, I tried ‘“*/*”’ but showing up ‘No apps can perform this action’ . So I tried to add the intent-filter,May be this is just only my problem?

**Comment by yasirkula** [comment]
`NativeFilePicker.PickFile( callback, new string[] { "*/*" } );` is supposed to work on Android. Can I see your code that uses `*/*` without declaring any intent-filters?

**Comment by andysdds** [comment]
Sorry for taking so long to reply.
`        extUTI = "*/*";
`
and 
`NativeFilePicker.PickFile((path) =>
                {
                    if (path == null || Path.GetExtension(path) != ".rosz")
                    {
                        Debug.Log("Operation cancelled");
                        Loadroszpath = "Operation cancelled";
                        roszpath = "";
                    }
                    else
                    {

                        Debug.Log("Picked file: " + path);
                        Loadroszpath = Path.GetFileName(path);
                        roszpath = path;
                    }
                }, new string[] { extUTI });`
When I run the android app without adding` intent-filter` , it showing up `no apps can perform this action` .

**Comment by yasirkula** [comment]
Your code works fine for me without any intent-filters on Galaxy S8. I suspect that only a fraction of Android devices suffer from this issue. You can try adding the following code in your Awake/Start function to see if resolves the issue for problematic devices, as well:

```csharp
using( var ajc = new AndroidJavaClass( "com.yasirkula.unity.NativeFilePickerPickFragment" ) )
	ajc.SetStatic( "pickerMode", 2 );
```

**Comment by Yiming075** [comment]
> `NativeFilePicker.PickFile( callback, new string[] { "*/*" } );` is supposed to work on Android. Can I see your code that uses `*/*` without declaring any intent-filters?

Is there any way to add custom extension on `ExportFile( string filePath, FilesExportedCallback callback = null )`?
When I export with the ".pc" extension it just said "no apps can perform this action"

**Comment by yasirkula** [comment]
@Yiming075 Can you replace `Plugins/NativeFilePicker/Android/NativeFilePicker.aar` with [this one](https://github.com/yasirkula/UnityNativeFilePicker/files/7191986/NativeFilePicker.zip) and see if it works (you need to unzip the _zip_ archive to find the new _aar_)?

**Comment by Yiming075** [comment]
Yes, it works. 👍

**Comment by yasirkula** [comment]
Awesome, I've published the fix with the latest commit.

**Pull request closed without merging**
